---
title: "Wakatobi SEM"
author: "Kelvin Gorospe"
output: 
  html_document:
    font-size: 8pt
---
<style type="text/css">

.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}

body, td {
   font-size: 14px;
}
code.r{
  font-size: 12px;
}
pre {
  font-size: 12px
}
</style>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```



```{r, message=FALSE}
rm(list=ls())
library(piecewiseSEM)
library(nlme) # Version 3.1.122
library(ggplot2)
library(corrplot)
library(car) #VIF calculations
library(vegan)

# Read-in organized data
setwd("~/Analyses/_RESULTS/SES-SEM/__Organized Data")
alldat.site<-read.csv("data_wakatobi_allDataMerged_10kmHumans.csv")

############################################################################################################
## The following adds flexibility to choose different response variables (fish ecology metrics) for the SEM
############################################################################################################
responseDF<-as.data.frame(cbind(fish.response=c("log_biomass_g", "biomass_g", "no_of_species", "shannon", 
                                                "invsimpson", "SimpsonEvenness"),
                                fish.title=c("log Total Biomass (g)", "Total Biomass (g)", "Richness", 
                                             "Shannon Diversity (H')", "Inverse Simpson's Diversity (D2)", 
                                             "Simpson's Evenness (E)" )))
## Identify fish response column name and title
## CHOICES:
## for biomass, set as biomass_g
## for log biomass, set as log_biomass_g
## for species richness, set as no_of_species
## for shannon diversity, set as shannon
## for inverse simpson's, set as invsimpson
## for simpson's evenness, set as SimpsonEvenness
fish.col<-"biomass_g" # Set response here
fish.row<-responseDF$fish.response %in% fish.col
fish.title<-as.character(responseDF[fish.row, "fish.title"])

# NEXT: Plot scatterplots
# First, create df scatter.final with all response + predictor variables + hierarchical variables
otherresponse<-responseDF$fish.response[!responseDF$fish.response %in% fish.col]
nonpredictors<-names(alldat.site) %in% c("site_id", "Site.Name", as.character(otherresponse))
scatter.final<-alldat.site[,!nonpredictors]
loc.col<-grep("location", names(scatter.final))
response.col<-grep(fish.col, names(scatter.final))
scatter.names<-names(scatter.final)[-c(loc.col, response.col)]

########################################################################################
########################################################################################
########################################################################################
# Set graph names here: should match object scatter.names
scatter.titles<-c( # Site metadata
"Latitude", "Longitude", "Exposure", "Visibility", "Reef Type",  
                  
# Fish Landings (catch) data
"Mean Landings", "Mean Personal", "Mean Pengumpul", "Mean Papalele", "Mean Market", "Mean On-Island", 
"Total Landings", "Total Personal", "Total Pengumpul", "Total Papalele", "Total Market", "Total On-Island", 
"Proportion Personal", "Proportion Pengumpul", "Proportion Papalele", "Proportion Market", "Proportion On-Island",
                  
# Benthic cover data
"Rugosity",
"Dead Coral With Algae", "Macroalgae", "Rubble", "Rock", "Soft Coral", "Sand", 
"All Hard Coral", "All Abiotic Substrate",
                  
# Oceanography data (from MSEC)
"NPP (Mean)", "NPP (Min)", "NPP (Max)", "NPP (SD)", "NPP (Interannual SD)",
"Reef Area within 5km", 
"Wave Energy (Mean)", "Wave Energy (SD)", "Wave Energy (Interannual SD)", 
"Wind Fetch", 

# SST data
"SST SD", "SST 50th Percentile", "SST 98th Percentile", "SST 2nd Percentile", "SST Kurtosis", "SST Skewness",
                  
# Human Population data
"Population", "Fishers", "Rowboats", "Motorboats"
)
```


```{r}

# Create scatterplots
for(i in 1:length(scatter.names))
{
  newfile=paste("plot_scatter_", fish.col, "_vs_", scatter.names[i], ".pdf", sep="")
  p<-ggplot(data=scatter.final, aes(x=get(scatter.names[i]), y=get(fish.col))) + 
    geom_point(aes(x=get(scatter.names[i]), y=get(fish.col), color=location, shape=type_reef), size=2) +
    labs(y=fish.title, x=scatter.titles[i]) +  
    theme_light()+
    theme(text = element_text(size=18), 
          legend.position="right")
  

  print(p)      
}

```

```{r kable}
##### CALCULATE CORRELATIONS and VIF
##### NOTE: Correlations and VIF are unaffected by scaling (which preserves the shape and spread of data)
##### i.e., scaling can wait until the last step

##### Remove discreet variables
discreetvar<-match(c("wave_wind_fetch", "type_reef", "exposed"), scatter.names)
corr.names<-scatter.names[-discreetvar]
corr.final<-scatter.final[corr.names]

##### Rename rows and columns for correlation plots
discreetvar.titles<-match(c("Wind Fetch", "Reef Type", "Exposure"), scatter.titles)
corr.titles<-scatter.titles[-discreetvar.titles]
colnames(corr.final)<-corr.titles


cor.dat<-cor(corr.final)
write.csv(cor.dat, file="_Table_CorrelationsPearson.csv")
cor.test<-abs(cor.dat)>0.5
write.csv(cor.test, file="_Table_CorrelationsTestPearson.csv")

# Spearman's for all ranked, ordered vars (e.g., DACOR data)
cor.spear<-cor(corr.final, method="spearman")
write.csv(cor.spear, file="_Table_CorrelationsSpearman.csv")
cor.spear.test<-abs(cor.spear)>0.5
write.csv(cor.spear.test, file="_Table_CorrelationsTestSpearman.csv")

# Generate p values and confidence intervals for each correlation pair
pvals<-cor.mtest(corr.final, conf.level=0.95)
corrplot(cor.dat, method="color", tl.col="black", tl.cex=0.5, number.cex=0.4, p.mat=pvals$p, sig.level=0.05, insig="blank", cl.align.text="r", addgrid.col="grey")


### Test for MULTICOLLINEARITY (calculate VIF)
### Equations for MULTICOLLINEARITY can be recycled as PSEM equations
analysis.col<-grep(fish.col, names(alldat.site))

### FIRST, construct simple model that only uses site-level data (i.e., no fish landings data)
form1a<-as.formula(paste(names(alldat.site)[analysis.col], " ~ All_HardCoral + reef_area_5km", sep=""))
form1b<-as.formula("All_HardCoral ~ SST_98perc + Population_2017")

fit1a <- lm(form1a, data=alldat.site)
fit1b <- lm(form1b, data=alldat.site)

# Note: only need to calculate vif for formulas with at least two predictors
vif(fit1a)
vif(fit1b)

################################################################################
################################################################################
# STRUCTURAL EQUATION MODELS
################################################################################
################################################################################
# PSEM of site-level data only (i.e., no fish landings data)

### SUBSET only model variables from alldat
all.forms_1<-ls(pattern="form1")
all.vars_1<-all.vars(get(all.forms_1[1]))
for (i in 2:length(all.forms_1))
{
  vars_i<-all.vars(get(all.forms_1[i]))
  all.vars_1<-append(all.vars_1, vars_i)    
}
model.vars_1<-unique(all.vars_1)

sem.vars.site<-alldat.site[c("location", "type_reef", model.vars_1)]
sem.site.scaled<-as.data.frame(apply(sem.vars.site[model.vars_1], 2, scale))
sem.site.scaled<-cbind(sem.vars.site$location, sem.vars.site$type_reef, sem.site.scaled)
names(sem.site.scaled)[1:2]<- c("location", "reef_type")

waka.sitelevel.psem<-psem(lm(form1a, data=sem.site.scaled), lm(form1b, data=sem.site.scaled)); 
summary(waka.sitelevel.psem, .progressBar = F, digits=2)



## Site-level PSEM with reef_type hierarchy
waka.sitelevel.reeftype.psem<-psem(lme(form1a, random = ~ 1 | reef_type, data=sem.site.scaled), 
                      lme(form1b, random = ~ 1 | reef_type, data=sem.site.scaled))

summary(waka.sitelevel.reeftype.psem, .progressBar = F)


```


